### ISSUE TITLE
Enhancement: Allow docked window to be on right side

### ISSUE THREAD

**Issue by Zeggpold** [Lej77/tree-style-tab-in-separate-window#11]
I'd like to have the "docked" window the right side instead of the left.  I know I unselect the docking preference, but in that case the window starts out enormously wide, and while I can shrink it to some extent, it won't shrink to as narrow as the docked window is.

**Comment by Lej77** [comment]
You should probably still use the docked window mode, but check the `Open the window to the right of the main window instead of the left` in the `Open beside current window` area in the `Docked Window Settings` section in the addon's option page.

**Comment by Zeggpold** [comment]
Thanks, that's exactly what I want.  No sure how I missed that whole set of options...
