### ISSUE TITLE
Simulate Docking: Open Side-by-Side without Addressbar

### ISSUE THREAD

**Issue by PowerWeb5** [Lej77/tree-style-tab-in-separate-window#2]
When opening Tree Style Tab in Separate Window, I always end up with window that is maximized and has address bar, etc. and even shows 3 the Sidebar open for Tree Style Tabs right next to the full-sized Tree Style Tabs page (resulting in Tree Style Tab trees total).

You can see that in the screenshot below of the result after I click Tree Style Tabs in Separate Window toolbar button:

![image](https://user-images.githubusercontent.com/4053734/50059853-13e83d80-0141-11e9-96e2-192f6b506964.png)

And here is screenshot from right before I click that button:

![image](https://user-images.githubusercontent.com/4053734/50059858-2e221b80-0141-11e9-86bb-99847f39137e.png)

The way it opens now makes it entirely useless.

**Suggested Changes**
Instead, Tree Style Tabs in Separate Window should:

1. Open Tree Style Tab in a new window **with all chrome hidden** (including: address bar, toolbar, sidebar, etc.)
2. Resize the current window and the new window and position them side-by-side (unmaximizing as necessary) similar to [Sidebar+](https://addons.mozilla.org/en-US/firefox/addon/sidebar_plus/?src=search) (by default, but can disable in options)
3. Optionally keep the positions and size in sync as you resize either window (also like Sidebar+) (maybe should also enable by default)

**JavaScript Example for Opening Tab without Addressbar**

```
var url = 'moz-extension://d9f19977-38ac-4464-a14f-a0309441d127/sidebar/sidebar.html';

//window.open(url,'Tabs Tree','directories=no,titlebar=no,toolbar=no,location=no,status=no,menubar=no,scrollbars=no,resizable=no,width=400,height=350');

  var creating = browser.windows.create({
    url: url,
    type: "popup",  // or "normal" or "panel" or "detached_panel"
    height: 200,
    width: 200
  });
//creating.then(onCreated, onError);
```

**Reference Extensions**
1. Sidebar+ with options to auto resize windows and simulate "docking" them

**My Configuration**
- Firefox Nightly 66.0a1 (2018-12-15) (64-bit)
- Windows 10 Pro x64
- Tree Style Tab in Separate Window v2.0
- Tree Style Tab v2.7.1

**Comment by Lej77** [comment]
This has been implemented and is available in version 3.0 of the extension.
