### ISSUE TITLE
Firefox Always Starts with Full Browser Resized to Tiny Docked Tabs Window Size & Position

### ISSUE THREAD

**Issue by PowerWeb5** [Lej77/tree-style-tab-in-separate-window#3]
For v3.0, when have Tree Style Tabs opened in separate Docked Window, after I close the main browser window and then restart Firefox, the main browser window ends up in the same size and position of the Tree Style Tabs window. This is because the Tabs window is always the last window closed and therefore the one that has its last window size & position persisted to use on next browser startup. 

### Severity

This is a critical issue, as most wont know of that work around, and shouldn't have to manually close Tree Style Tabs window first and then main browser window, or often forget or by habit fail to do so even if know of that workaround.

### Screenshot

You can see this issue in the screenshot below,  showing how Firefox browser window ends up thin and positioned on left side the screen the next time I startup Firefox, which was the size and position of the Tree Style Tabs window opened and docked by this extension, instead of starting up with the main browser window's size and position (which was all the rest of the screen), as should be the case.

![image](https://user-images.githubusercontent.com/4053734/50203829-a6dad080-0317-11e9-80de-79eeedb3563f.png)

### Suggested Fix Alternatives

Can you work around this, possibly via one of the following methods?

1. Close associated Tabs window *before* the browser window is closed, by handling main browser window's closing event (eg. window.onRemoved for main browser window), to ensure main browser window size & position is persisted instead of that for Tabs window (and potentially even speed up or avoid this delaying browser exit somewhat like does now)?

2. Configure the Sidebar window to ensure treated like a secondary window, possibly with window.type = popup | panel | app | devtools (instead of "normal") (or if not, maybe window.state = docked, even if treated like state = normal) (or possible and if not an option to change  (or even override it's ID so isn't position isn't persisted as the "chrome://browser/content/browser.xul#main-window")?

3. Or quickly resize the Tabs window before auto-closing it (if it's the last window), to match the last known browser window size + position (and maybe maximized state), so that the actual browser window size and position gets persisted instead? You could track the last known browser window position in closing (eg. windows.onRemoved) event handler ideally (or else, in worst case, when performing periodic eg. 1000msec docking position check).

### Reference Details

For reference, it seems that for Firefox the last browser window size and position (persisted and used for default startup position the next time you launch Firefox) are saved to the xulstore.json file in your profile folder, found at the very start of that file, like:

`{"chrome://browser/content/browser.xul":{"main-window":{"width":"486","height":"1040","screenX":"0","screenY":"0","sizemode":"normal","aiosOpen":"true","aiosVButtons":"true"}`

### Configuration

- I have "The opened window should be docked to the current window" setting enabled
- Other settings as defaults, like with "Open the sidebar page in a new window", "Create the new window beside the current window", and "Close sidebar as well", "Minimize sidebar as well", and "Simulate docking" (1000msec) all enabled.
-Tree Style Tab in Separate Window v3.0
-Tree Style Tab v2.7.2
-Firefox Nightly 66.0a1 (2018-12-18) (64-bit)
-Windows 10 Pro x64

### Related Issue:  Remembering Tab Window Width

Also, the width of the Tabs Window fails to be remembered when have "Width of the created window" = -1, so that if I resize it (via dragging left edge of Tree Tabs window), then close that Tree Tabs window, then open another one, it still has the too-small hard-coded default width.
Settings.  

- The only work around is to guess the current windows width and then enter in "Width of the created window" then close and reopen and repeat until I get back to the original width I had resized to visually with mouse, and then repeating this every time I need to resize for different monitor or if need more space or longer tab titles, and then back again later.
	
- Instead it should remember your last used (after manual resizing) Tree Tabs window width, saving to the Width of the created window setting by default, unless uncheck "Always remember last width (saved to above setting)" checkbox setting.
	
### Related Issue: Auto Applying Width/Settings Changes

Also, changing the width in Settings or other kinds of Settings should auto-resize the window or otherwise be applied immediately (or at next 1000msec docking check) without having to manually close and recreate it each time (or resize browser much smaller than larger again or vice versa).

**Comment by Lej77** [comment]
I have release a new version of the extension (v3.1) that should fix all of these issues. 

Regarding you suggested fixes:
1. As far as I know it is not possible to close another window before the window that was closed by the user. The `browser.windows.onRemoved` event is triggered after the window is closed so then it is already too late.
2. I tried using different window types but non of them seemed to fix the issue.
3. I implemented a fix based on this suggestion. The `browser.windows.onRemoved` event only provided a window id and no actual window info so therefore I had no choice but to use the parent information from the last docking position check.

####  Remembering Tab Window Width & Auto Applying Width/Settings Changes
An extra option was added to sync the width of all sidebar windows (enabled by default) that also syncs to the new window width setting so that changing that setting will change the open sidebar windows width.
